# NumPy
NumPy is a fundamental library for scientific computing in python. it provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [3]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
## 1 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
  arr2=np.array([[1,2,3,4,5]])
  arr2.shape

(1, 5)

In [9]:
  ## 2 d array
  arr2=np.array([[1,2,3,4,5],[5,6,4,8,9]])
  print(arr2)
  print(arr2.shape)

[[1 2 3 4 5]
 [5 6 4 8 9]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## attribute of numpy array

arr =  np.array([[1,2,3],[5,8,9]])

print("array:\n",arr)
print("shape",arr.shape)
print("number of dimensions:",arr.ndim)
print("size(number of elements):",arr.size)
print("data type:",arr.dtype)
print("item size (in bytes):",arr.itemsize)

array:
 [[1 2 3]
 [5 8 9]]
shape (2, 3)
number of dimensions: 2
size(number of elements): 6
data type: int64
item size (in bytes): 8


In [20]:
## numpy vectorized operation
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([100,200,300,400,500,600])

## element wise addition
print("addition:",arr1+arr2)

## element wise substraction
print("substraction",arr1-arr2)

## element wise multiplication
print("multiplication",arr1*arr2)

## element wise division
print("division",arr1/arr2)

addition: [101 202 303 404 505 606]
substraction [ -99 -198 -297 -396 -495 -594]
multiplication [ 100  400  900 1600 2500 3600]
division [0.01 0.01 0.01 0.01 0.01 0.01]


In [21]:
## universal function

arr=np.array([2,3,6,8,10])
## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.44948974 2.82842712 3.16227766]
[7.38905610e+00 2.00855369e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[ 0.90929743  0.14112001 -0.2794155   0.98935825 -0.54402111]
[0.69314718 1.09861229 1.79175947 2.07944154 2.30258509]


In [22]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array : \n",arr)

array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [27]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [25]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
## modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [31]:
arr[:]=100
print(arr)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [32]:
## statistical concepts--Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

## calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

## normalize the data
normalized_data=(data-mean)/std_dev
print("nomalized data:",normalized_data)

nomalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [34]:
data =  np.array([1,2,3,4,5,6,7,8,9,10])

## mean
mean = np.mean(data)
print("mean:",mean)

## median
median = np.median(data)
print("median:",median)

## standard deviation
std_dev = np.std(data)
print("standard deviation:",std_dev)

## variance
variance = np.var(data)
print("variance:",variance)

mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


In [43]:
## logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data>5
data[(data>=5) & (data<=9)]

array([5, 6, 7, 8, 9])